### ISSUE TITLE
bug!!

### ISSUE THREAD

**Issue by yifungkhong** [jedsoft/jed#4]
https://github.com/jedsoft/jed/blob/33f47575fa922c10affa8a4aea70702003e5bdab/src/screen.c#L1211

s2 should be s1

**Comment by jedsoft** [comment]
Corrected in commit [3d67559].

This typo has been there for a very long time.  Did you find it by looking at the source code itself?  Or did it manifest itself in the editor?  I suspect the former.

Thanks

**Comment by yifungkhong** [comment]
> Corrected in commit [[3d67559](https://github.com/jedsoft/jed/commit/3d67559d9df9e8886fc51a99c6d730921cb99a5e)].
> 
> This typo has been there for a very long time. Did you find it by looking at the source code itself? Or did it manifest itself in the editor? I suspect the former.
> 
> Thanks

yes,I just found it by examining the source code
