### ISSUE TITLE
editor crash when execute query_replace_match

### ISSUE THREAD

**Issue by yifungkhong** [jedsoft/jed#5]
it crashes when replacing regular expression like \\(foo\\) with back reference \\&, it occurs in 
https://github.com/jedsoft/jed/blob/3d67559d9df9e8886fc51a99c6d730921cb99a5e/src/search.c#L551 follow lines cause index out of range exception

on the side:what does \\& do in regexp? does it mean the first matched group?

**Comment by jedsoft** [comment]
I believe that the latest commit (pre0.99.20-179) fixes the bug.

In this context, \& means that it matches the entire match.  For example, replacing
`\([a-z]+\)\(\d+\)` with `\& --> \1 \2`, will change
`  item1234`
to
`  item1234 --> item 1234`

Thanks for reporting it.
