### ISSUE TITLE
JED does not always recognize the extent of wide UTF-8 characters (such as LOTUS)

### ISSUE THREAD

**Issue by kseistrup** [jedsoft/jed#9]
### Problem

When I [in a terminal emulator under X.org] edit a text that contains certain UTF-8 wide characters, such as LOTUS / U+1FAB7 / f0 9f aa b7, jed seems to get confused about what character is beneath its cursor, even when “standing” on an ASCII character. This often leads to unintended deletions:

```sh
» python -c "print('\N{LOTUS} ABC')" > lotus.txt
» cat lotus.txt
🪷 ABC
» jed lotus.txt  # now delete the ‘B’ and save the result
» cat lotus.txt
🪷 AB
```

### How to reproduce

1. Produce a file containing one line: 🪷 ABC
2. In jed, delete the B,
  a. either by placing the cursor over the C and use BACKSPACE,
  b. or by placing the cursor over the B and delete the character under the cursor,
  c. then save and quit.
3. Confirm, e.g. by cat'ing the file, that the wrong character has been deleted.

It may also be noticed that the cursor may be moving eratically when trying to position it over the B or the C (or the A, for that matter).

### Expected behaviour

In the example above, jed should delete the B and the line should then read: 🪷 AC

### Notes

The screenshots below show `jed` in the VTE3 based terminal emulator `terminator` in the window manager `qtile` running in X.org on Linux.

Jed gets it right when launched in the login TTY on Linux, before the X.org graphical interface has been started.

Xjed gets the deletion right (but fails to display the LOTUS (something that _could_ be a font problem — `xjed` is launched thusly: `xjed -fn 'Source Code Pro' -fs 13 lotus.txt`)).

The problem has also been noticed in these terminal emulators (some of which are VTE3 based, some not):

+ alacritty
+ sakura
+ urxvt (rxvt-unicode)
+ wezterm
+ xterm

### Software & environment

```sh
» jed --version
jed version: pre0.99.20-180/Unix
 Compiled with GNU C 13.2
S-Lang version: pre2.3.4-9

jed compile-time options:
 +LINE_ATTRIBUTES +BUFFER_LOCAL_VARS +SAVE_NARROW +TTY_MENUS
 +EMACS_LOCKING +MULTICLICK +SUBPROCESSES +DFA_SYNTAX +ABBREVS
 +COLOR_COLUMNS +LINE_MARKS +GPM_MOUSE +IMPORT

Using JED_ROOT=/usr/share/jed
» echo $TERM
xterm-256color
» echo $LANG
en_DK.UTF-8
» echo $LC_ALL
en_DK.UTF-8
```

The first screenshot shows jed with the cursor positioned over the B:

![lotus-1](https://github.com/jedsoft/jed/assets/25586/f377cffa-d45e-42ca-ad42-939a899960ef)

The second screenshot shows jed when the B (but _not_ the C) has been deleted:

![lotus-2](https://github.com/jedsoft/jed/assets/25586/dde28b5e-8394-4ca7-8d8f-db257c2bb38b)

----

edit: typo

**Comment by jedsoft** [comment]
Hi Klaus,

This is actually a slang issue.  The currently released version uses
version 10 of the Unicode tables, but the U+1FAB7 was not introduced
until version 14.  The latest snapshot of the slang library uses
the version 15 unicode tables.  Please try the version from

  <http://www.jedsoft.org/snapshots/>

Thanks,
--John

On Tue, 20 Feb 2024 02:04:14 -0800, Klaus Alexander Seiﬆrup ***@***.***> said:
>### Problem
>
>When I [in a terminal emulator under X.org] edit a text that contains certain
>UTF-8 wide characters, such as LOTUS / U+1FAB7 / f0 9f aa b7, jed seems to get
>confused about what character is beneath its cursor, even when
>âstandingâ on an ASCII character. This often leads to
>unintended deletions:
>
>```sh
>Â» python -c "print('\N{LOTUS} ABC')" > lotus.txt
>Â» cat lotus.txt
>ðª· ABC
>Â» jed lotus.txt  # now delete the âBâ and save the result
>Â» cat lotus.txt
>ðª· AB
>```
>
>### How to reproduce
>
>1. Produce a file containing one line: ðª· ABC
>2. In jed, delete the B,
>  a. either by placing the cursor over the C and use BACKSPACE,
>  b. or by placing the cursor over the B and delete the character under the
>  cursor,
>  c. then save and quit.
>3. Confirm, e.g. by cat'ing the file, that the wrong character has been
>deleted.
>
>It may also be noticed that the cursor may be moving eratically when trying to
>position it over the B or the C (or the A, for that matter).
>
>### Expected behaviour
>
>In the example above, jed should delete the B and the line should then read:
>ðª· AC
>
>### Notes
>
>The screenshots below show `jed` in the VTE3 based terminal emulator
>`terminator` in the window manager `qtile` running in X.org on Linux.
>
>Jed gets it right when launched in the login TTY on Linux, before the X.org
>graphical interface has been started.
>
>Xjed gets the deletion right (but fails to display the LOTUS (something that
>_could_ be a font problem â `xjed` is launched thusly: `xjed -fn
>'Source Code Pro' -fs 13 lotus.txt`)).
>
>The problem has also been noticed in these terminal emulators (some of which
>are VTE3 based, some not):
>
>+ alacritty
>+ sakura
>+ urxvt (rxvt-unicode)
>+ wezterm
>+ xterm
>
>### Software & environment
>
>```sh
>Â» jed --version
>jed version: pre0.99.20-180/Unix
> Compiled with GNU C 13.2
>S-Lang version: pre2.3.4-9
>
>jed compile-time options:
> +LINE_ATTRIBUTES +BUFFER_LOCAL_VARS +SAVE_NARROW +TTY_MENUS
> +EMACS_LOCKING +MULTICLICK +SUBPROCESSES +DFA_SYNTAX +ABBREVS
> +COLOR_COLUMNS +LINE_MARKS +GPM_MOUSE +IMPORT
>
>Using JED_ROOT=/usr/share/jed
>Â» echo $TERM
>xterm-256color
>Â» echo $LANG
>en_DK.UTF-8
>Â» echo $LC_ALL
>en_DK.UTF-8
>```
>
>The first screenshot shows jed with the cursor positioned over the B:
>
>![lotus-1](https://github.com/jedsoft/jed/assets/25586/f377cffa-d45e-42ca-ad
>42-939a899960ef)
>
>The second screenshot shows jed when the B (but _not_ the C)has been deleted:
>
>![lotus-2](https://github.com/jedsoft/jed/assets/25586/dde28b5e-8394-4ca7-8d
>8f-db257c2bb38b)
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/jedsoft/jed/issues/9
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>

----next-part-D027A91765D56A5D15DF674F723FF0--

**Comment by kseistrup** [comment]
Thanks John. I can confirm that using `slang-pre2.3.4-10` indeed solves the problem. Wonderful!

I'm curious: How come xjed knew how to erase the correct, and only the correct, character under the cursor when my jed and xjed were both using the same S-Lang library? Does xjed use some X library functions under the hood that relies on some other unicode table?

**Comment by kseistrup** [comment]
Having run with snapshot 10 for 5 days now, and seen no problems, I consider this issue solved and will close it with this comment.
